var keyMirror = require('keymirror');

module.exports = keyMirror({
	ADD_POKEMON: null,
	ADD_POKEMON_SUCCESS: null,
	ADD_POKEMON_FAIL: null,
	REMOVE_POKEMON: null,

	LOAD_POKEMON_GEN_NAMES: null,
	LOAD_POKEMON_GEN_NAMES_SUCCESS: null,
	LOAD_POKEMON_GEN_NAMES_FAIL: null,

	CHANGE_GENERATION: null,
	CHANGE_FORMAT: null,
	LOAD_ALL_GENS_AND_FORMATS: null,
	LOAD_ALL_GENS_AND_FORMATS_SUCCESS: null,
	LOAD_ALL_GENS_AND_FORMATS_FAIL: null
});
